modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://"

[[mods]]
modId="magic"
version="${file.jarVersion}"
displayName="Magic Mod"
updateJSONURL="http://"
displayURL="http://"
logoFile="examplemod.png"
credits="Do you want to use the Magic?"
authors=""

description=''

[[dependencies.magic]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.magic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
